version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-228-250-82.eu-west-1.compute.amazonaws.com
            database: dctcaf773e0nqt
            schema: public
            user: gjorzqxkgxxjzo
            password: 8c23b97ce3fe993cb827ca24934433d823e18d471acc8fefdf3810e4d99d4c31
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true